/**
 * Canonical HTTP paths for the LocalPro API.
 * Keep in sync with `api-reference.md` at the repo root.
 */
export const API = {
  auth: {
    register: '/api/auth/register',
    login: '/api/auth/login',
    logout: '/api/auth/logout',
    refresh: '/api/auth/refresh',
    phoneSend: '/api/auth/phone/send',
    phoneVerify: '/api/auth/phone/verify',
    facebook: '/api/auth/facebook',
    facebookCallback: '/api/auth/facebook/callback',
    verifyEmail: '/api/auth/verify-email',
    forgotPassword: '/api/auth/forgot-password',
    resetPassword: '/api/auth/reset-password',
    me: '/api/auth/me',
    meAvatar: '/api/auth/me/avatar',
    meAddress: '/api/auth/me/addresses',
    meAddressById: (id: string) => `/api/auth/me/addresses/${id}`,
    mePreferences: '/api/auth/me/preferences',
  },
  user: {
    settings: '/api/user/settings',
    deleteRequest: '/api/user/delete-request',
    export: '/api/user/export',
  },
  jobs: {
    list: '/api/jobs',
    create: '/api/jobs',
    byId: (id: string) => `/api/jobs/${id}`,
    cancel: (id: string) => `/api/jobs/${id}/cancel`,
    fund: (id: string) => `/api/jobs/${id}/fund`,
    fundWallet: (id: string) => `/api/jobs/${id}/fund-wallet`,
    start: (id: string) => `/api/jobs/${id}/start`,
    markComplete: (id: string) => `/api/jobs/${id}/mark-complete`,
    complete: (id: string) => `/api/jobs/${id}/complete`,
    partialRelease: (id: string) => `/api/jobs/${id}/partial-release`,
    quotes: (id: string) => `/api/jobs/${id}/quotes`,
    withdraw: (id: string) => `/api/jobs/${id}/withdraw`,
    milestones: (id: string) => `/api/jobs/${id}/milestones`,
    milestoneRelease: (id: string, mId: string) => `/api/jobs/${id}/milestones/${mId}/release`,
  },
  quotes: {
    list: '/api/quotes',
    create: '/api/quotes',
    byId: (id: string) => `/api/quotes/${id}`,
    accept: (id: string) => `/api/quotes/${id}/accept`,
    reject: (id: string) => `/api/quotes/${id}/reject`,
  },
  quoteTemplates: {
    list: '/api/quote-templates',
    create: '/api/quote-templates',
    byId: (id: string) => `/api/quote-templates/${id}`,
  },
  messages: {
    list: '/api/messages',
    threads: '/api/messages/threads',
    thread: (threadId: string) => `/api/messages/${threadId}`,
    threadPost: (threadId: string) => `/api/messages/${threadId}`,
    threadAttachment: (threadId: string) => `/api/messages/${threadId}/attachment`,
    stream: (threadId: string) => `/api/messages/stream/${threadId}`,
  },
  notifications: {
    list: '/api/notifications',
    patchBulk: '/api/notifications',
    byId: (id: string) => `/api/notifications/${id}`,
    read: (id: string) => `/api/notifications/${id}/read`,
    stream: '/api/notifications/stream',
    preferences: '/api/notifications/preferences',
    registerToken: '/api/notifications/register-token',
  },
  payments: {
    create: '/api/payments',
    bySession: (sessionId: string) => `/api/payments/${sessionId}`,
  },
  wallet: {
    get: '/api/wallet',
    transactions: '/api/wallet/transactions',
    topup: '/api/wallet/topup',
    topupVerify: '/api/wallet/topup/verify',
    withdraw: '/api/wallet/withdraw',
  },
  transactions: {
    list: '/api/transactions',
    export: '/api/transactions/export',
  },
  favorites: {
    list: '/api/favorites',
    create: '/api/favorites',
    byProvider: (providerId: string) => `/api/favorites/${providerId}`,
  },
  reviews: {
    list: '/api/reviews',
    create: '/api/reviews',
    respond: (id: string) => `/api/reviews/${id}/respond`,
    moderate: (id: string) => `/api/reviews/${id}/moderate`,
    byProvider: (providerId: string) => `/api/providers/${providerId}/reviews`,
  },
  disputes: {
    list: '/api/disputes',
    create: '/api/disputes',
  },
  kyc: {
    submit: '/api/kyc',
  },
  search: {
    query: '/api/search',
  },
  skills: {
    list: '/api/skills',
  },
  categories: {
    list: '/api/categories',
  },
  announcements: {
    list: '/api/announcements',
  },
  loyalty: {
    get: '/api/loyalty',
    referral: '/api/loyalty/referral',
    redeem: '/api/loyalty/redeem',
  },
  recurring: {
    list: '/api/recurring',
    create: '/api/recurring',
    pastProviders: '/api/recurring/past-providers',
    byId: (id: string) => `/api/recurring/${id}`,
    savedMethod: '/api/recurring/saved-method',
  },
  consultations: {
    list: '/api/consultations',
    create: '/api/consultations',
    byId: (id: string) => `/api/consultations/${id}`,
    respond: (id: string) => `/api/consultations/${id}/respond`,
    messages: (id: string) => `/api/consultations/${id}/messages`,
    convertToJob: (id: string) => `/api/consultations/${id}/convert-to-job`,
  },
  providers: {
    /** Unauthenticated browse — see MOBILE_PROVIDERS_IMPLEMENTATION_GUIDE.md */
    publicList: '/api/public/providers',
    list: '/api/providers',
    /** Public directory search (`q`, `skill`, `page`, `limit`) — see MOBILE_PROVIDER_DISCOVERY_GUIDE.md */
    search: '/api/providers/search',
    profileById: (id: string) => `/api/providers/${id}/profile`,
    myProfile: '/api/providers/profile',
    updateProfile: '/api/providers/profile',
    generateBio: '/api/providers/profile/generate-bio',
    serviceAreas: '/api/providers/profile/service-areas',
    serviceAreaById: (id: string) => `/api/providers/profile/service-areas/${id}`,
  },
  providerBoost: {
    get: '/api/provider/boost',
    create: '/api/provider/boost',
    byId: (id: string) => `/api/provider/boost/${id}`,
  },
  providerTraining: {
    list: '/api/provider/training',
    byId: (id: string) => `/api/provider/training/${id}`,
    enroll: (id: string) => `/api/provider/training/${id}/enroll`,
    checkout: (id: string) => `/api/provider/training/${id}/checkout`,
    activate: (id: string) => `/api/provider/training/${id}/activate`,
    certificate: (id: string) => `/api/provider/training/${id}/certificate`,
    enrollments: '/api/provider/training/enrollments',
    enrollmentComplete: (enrollmentId: string) => `/api/provider/training/enrollments/${enrollmentId}/complete`,
    enrollmentLessonComplete: (enrollmentId: string, lessonId: string) =>
      `/api/provider/training/enrollments/${enrollmentId}/lessons/${lessonId}/complete`,
  },
  providerAgency: {
    upgrade: '/api/provider/upgrade-agency',
    dashboard: '/api/provider/agency/dashboard',
    profile: '/api/provider/agency/profile',
    staff: '/api/provider/agency/staff',
    staffDelete: '/api/provider/agency/staff',
    invites: '/api/provider/agency/invites',
    jobs: '/api/provider/agency/jobs',
    jobAssign: (id: string) => `/api/provider/agency/jobs/${id}/assign`,
    jobStatus: (id: string) => `/api/provider/agency/jobs/${id}/status`,
    earnings: '/api/provider/agency/earnings',
    payouts: '/api/provider/agency/payouts',
    analytics: '/api/provider/agency/analytics',
    reviews: '/api/provider/agency/reviews',
    quotations: '/api/provider/agency/quotations',
    clients: '/api/provider/agency/clients',
    services: '/api/provider/agency/services',
    schedule: '/api/provider/agency/schedule',
    equipment: '/api/provider/agency/equipment',
    compliance: '/api/provider/agency/compliance',
    billing: '/api/provider/agency/billing',
    billingCheckout: '/api/provider/agency/billing/checkout',
    billingConfirm: '/api/provider/agency/billing/confirm',
    settings: '/api/provider/agency/settings',
    staffPerformance: '/api/provider/agency/staff/performance',
  },
  agencyInvite: {
    byToken: (token: string) => `/api/agency/invite/${token}`,
    accept: (token: string) => `/api/agency/invite/${token}/accept`,
  },
  support: {
    list: '/api/support',
    create: '/api/support',
    attachment: '/api/support/attachment',
    stream: '/api/support/stream',
    tickets: '/api/support/tickets',
    ticketCreate: '/api/support/tickets',
    ticketById: (id: string) => `/api/support/tickets/${id}`,
  },
  knowledge: {
    list: '/api/knowledge',
    byId: (id: string) => `/api/knowledge/${id}`,
  },
  apply: {
    list: '/api/apply',
    create: '/api/apply',
    byJobId: (jobId: string) => `/api/apply/${jobId}`,
  },
  upload: {
    post: '/api/upload',
  },
  payouts: {
    list: '/api/payouts',
    create: '/api/payouts',
  },
  recommendations: {
    maintenance: '/api/recommendations/maintenance',
  },
  business: {
    upgrade: '/api/client/upgrade-business',
    org: '/api/business/org',
    dashboard: '/api/business/dashboard',
    jobs: '/api/business/jobs',
    jobsBulk: '/api/business/jobs/bulk',
    jobsRecurring: '/api/business/jobs/recurring',
    members: '/api/business/members',
    membersActivity: '/api/business/members/activity',
    locations: '/api/business/locations',
    locationsDetail: '/api/business/locations/detail',
    preferredProviders: '/api/business/preferred-providers',
    disputes: '/api/business/disputes',
    escrow: '/api/business/escrow',
    billing: '/api/business/billing',
    billingCheckout: '/api/business/billing/checkout',
    billingConfirm: '/api/business/billing/confirm',
    analyticsExpenses: '/api/business/analytics/expenses',
    analyticsProviders: '/api/business/analytics/providers',
    analyticsBudgetAlerts: '/api/business/analytics/budget-alerts',
    analyticsReport: '/api/business/analytics/report',
  },
  ai: {
    classifyCategory: '/api/ai/classify-category',
    estimateBudget: '/api/ai/estimate-budget',
    generateDescription: '/api/ai/generate-description',
    suggestSkills: '/api/ai/suggest-skills',
    suggestReplies: '/api/ai/suggest-replies',
    generateQuoteMessage: '/api/ai/generate-quote-message',
    summarizeChat: '/api/ai/summarize-chat',
    generateConsultationDescription: '/api/ai/generate-consultation-description',
    summarizeDispute: '/api/ai/summarize-dispute',
    recommendProviders: '/api/ai/recommend-providers',
  },
  peso: {
    dashboard: '/api/peso/dashboard',
    workforce: '/api/peso/workforce',
    workforceExport: '/api/peso/workforce/export',
    jobs: '/api/peso/jobs',
    jobClose: (id: string) => `/api/peso/jobs/${id}/close`,
    referrals: '/api/peso/referrals',
    bulkOnboard: '/api/peso/bulk-onboard',
    providerVerify: (id: string) => `/api/peso/providers/${id}/verify`,
    providerCertifications: (id: string) => `/api/peso/providers/${id}/certifications`,
    groups: '/api/peso/groups',
    groupById: (id: string) => `/api/peso/groups/${id}`,
    officers: '/api/peso/officers',
    officerById: (id: string) => `/api/peso/officers/${id}`,
    emergency: '/api/peso/emergency',
    reports: '/api/peso/reports',
    export: '/api/peso/export',
    settings: '/api/peso/settings',
    settingsLogo: '/api/peso/settings/logo',
  },
  admin: {
    stats: '/api/admin/stats',
    jobs: '/api/admin/jobs',
    jobById: (id: string) => `/api/admin/jobs/${id}`,
    jobApprove: (id: string) => `/api/admin/jobs/${id}/approve`,
    jobReject: (id: string) => `/api/admin/jobs/${id}/reject`,
    jobCancel: (id: string) => `/api/admin/jobs/${id}/cancel`,
    jobForceWithdraw: (id: string) => `/api/admin/jobs/${id}/force-withdraw`,
    jobEscrowOverride: (id: string) => `/api/admin/jobs/${id}/escrow-override`,
    disputes: '/api/admin/disputes',
    disputeById: (id: string) => `/api/admin/disputes/${id}`,
    users: '/api/admin/users',
    usersExport: '/api/admin/users/export',
    usersImport: '/api/admin/users/import',
    usersBulk: '/api/admin/users/bulk',
    usersBulkMessage: '/api/admin/users/bulk/message',
    userById: (id: string) => `/api/admin/users/${id}`,
    userImpersonate: (id: string) => `/api/admin/users/${id}/impersonate`,
    impersonateExit: '/api/admin/impersonate/exit',
    userUnlock: (id: string) => `/api/admin/users/${id}/unlock`,
    userActivity: (id: string) => `/api/admin/users/${id}/activity`,
    userMessage: (id: string) => `/api/admin/users/${id}/message`,
    userResetPassword: (id: string) => `/api/admin/users/${id}/reset-password`,
    userWalletTransactions: (id: string) => `/api/admin/users/${id}/wallet-transactions`,
    userDuplicates: (id: string) => `/api/admin/users/${id}/duplicates`,
    userGdprExport: (id: string) => `/api/admin/users/${id}/gdpr-export`,
    userDelete: (id: string) => `/api/admin/users/${id}/delete`,
    kyc: '/api/admin/kyc',
    kycByUser: (userId: string) => `/api/admin/kyc/${userId}`,
    fraud: '/api/admin/fraud',
    payouts: '/api/admin/payouts',
    payoutById: (id: string) => `/api/admin/payouts/${id}`,
    walletWithdrawals: '/api/admin/wallet/withdrawals',
    walletWithdrawalById: (id: string) => `/api/admin/wallet/withdrawals/${id}`,
    staff: '/api/admin/staff',
    staffById: (id: string) => `/api/admin/staff/${id}`,
    categories: '/api/admin/categories',
    categoryById: (id: string) => `/api/admin/categories/${id}`,
    announcements: '/api/admin/announcements',
    announcementById: (id: string) => `/api/admin/announcements/${id}`,
    partners: '/api/admin/partners',
    partnerById: (id: string) => `/api/admin/partners/${id}`,
    businesses: '/api/admin/businesses',
    businessById: (id: string) => `/api/admin/businesses/${id}`,
    agencies: '/api/admin/agencies',
    agencyById: (id: string) => `/api/admin/agencies/${id}`,
    providerCertify: (userId: string) => `/api/admin/providers/${userId}/certify`,
    settings: '/api/admin/settings',
    featureFlags: '/api/admin/feature-flags',
    knowledge: '/api/admin/knowledge',
    knowledgeById: (id: string) => `/api/admin/knowledge/${id}`,
    courses: '/api/admin/courses',
    courseById: (id: string) => `/api/admin/courses/${id}`,
    support: '/api/admin/support',
    supportByUser: (userId: string) => `/api/admin/support/${userId}`,
    supportAttachment: (userId: string) => `/api/admin/support/${userId}/attachment`,
    supportStream: '/api/admin/support/stream',
    supportTickets: '/api/admin/support/tickets',
    accountingEntries: '/api/admin/accounting/entries',
    accountingTrialBalance: '/api/admin/accounting/trial-balance',
    accountingBalanceSheet: '/api/admin/accounting/balance-sheet',
    accountingIncomeStatement: '/api/admin/accounting/income-statement',
    accountingEscrowHoldings: '/api/admin/accounting/escrow-holdings',
    accountingProviderPayable: '/api/admin/accounting/provider-payable',
    accountingManualEntry: '/api/admin/accounting/manual-entry',
    accountingReconcile: '/api/admin/accounting/reconcile',
    ledgerReconcile: '/api/admin/ledger/reconcile',
    databaseStats: '/api/admin/database/stats',
    databaseBackup: '/api/admin/database/backup',
    backupSnapshots: '/api/admin/backup/snapshots',
    databaseRestore: '/api/admin/database/restore',
    databaseReset: '/api/admin/database/reset',
    migrateSkills: '/api/admin/migrate-skills',
  },
  public: {
    activityFeed: '/api/public/activity-feed',
    categoryDemand: '/api/public/category-demand',
    board: '/api/public/board',
    boardSettings: '/api/public/board-settings',
    jobById: (id: string) => `/api/public/jobs/${id}`,
    recentCompletions: '/api/public/recent-completions',
  },
  utility: {
    health: '/api/health',
    unsubscribe: '/api/unsubscribe',
    paymentReturn: '/api/payment-return',
    cspReport: '/api/csp-report',
  },
} as const;
